site_name: Islam Education
site_description: Clear, authentic and accessible knowledge about Islam
site_url: https://islam-education.com

theme:
  name: material
  language: en


extra_css:
  - stylesheets/extra.css




nav:
      - Home: index.md
      - What is Islam?: basic-knowledge/what-is-islam.md
      - Who is Muhammad ﷺ?: basic-knowledge/muhammad.md
      - The Qur’an: basic-knowledge/quran.md
      - The Five Pillars: basic-knowledge/five-pillars.md
      - Morals & Character: ethics-life/morals.md
      - Daily Life of a Muslim: ethics-life/daily-life.md
      - Common Misconceptions: clarifications/misconceptions.md
      - Islamic History: knowledge/history.md
      - Law (Basics): knowledge/law-basics.md
      - Spirituality (Ihsan): knowledge/spirituality.md
      - Videos: media/videos.md
      - About the Project: about/project.md
      - Support: about/support.md
