site_name: Islam Education
site_description: Clear and accessible knowledge about Islam
site_url: https://islam-education.com

docs_dir: .


theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Learn:
      - The Shahada: learn/shahada.md
  - About: about.md
