site_name: Islam Education
site_description: Clear, authentic and accessible knowledge about Islam
site_url: https://islam-education.com

theme:
  name: material
  palette:
  
    - scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

 features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - footer.hide_generator
    

extra_css:
  - stylesheets/extra.css




nav:
      - Home: index.md
      - What is Islam?: basic-knowledge/what-is-islam.md
      - Who is Muhammad ﷺ?: basic-knowledge/muhammad.md
      - The Qur’an: basic-knowledge/quran.md
      - The Five Pillars: basic-knowledge/five-pillars.md
      - Shahada: basic-knowledge/shahada.md
      - Zakat: basic-knowledge/zakat.md
      - Morals & Character: basic-knowledge/morals.md
      - Daily Life of a Muslim: basic-knowledge/daily-life.md
      - Common Misconceptions: basic-knowledge/misconceptions.md
      - Islamic History: basic-knowledge/history.md
      - Law (Basics): basic-knowledge/law-basics.md
      - Spirituality (Ihsan): basic-knowledge/spirituality.md
      - Videos: media/videos.md
      - About the Project: about/project.md
      - Support: about/support.md
